### ISSUE TITLE
Interval of snippets ?

### ISSUE THREAD

**Issue by wzmsltw** [yjxiong/action-detection#1]
Hi 
I am reading your CVPR2017 paper about action-detection recently, really a wonderful work. 
I have a problem about paper. You said in paper :" Given a video, a sequence of snippets will be extracted with a regular interval in between." I want to know the size of interval you used in both THUMOS14 and ActivityNet.
Thank you so much.

**Comment by yjxiong** [comment]
Hi @wzmsltw ,

Thanks for your interests in our works. The interval as mentioned in the paper is 6. The flow stack is formed by 5 frames, using an interval of 6 ensures we do not use redundant information.

**Comment by wzmsltw** [comment]
Hi @yjxiong ,
Thanks for you reply. It seems you almost calculate optical flow in each frame( interval is 6 while size of flow stack is 5). So how long it takes for calculating optical flow in full activity net 1.3?
And when will you release the codes? I am very looking forward to it~

**Comment by yjxiong** [comment]
It takes roughly one day with 8 Titan X.

**Comment by wzmsltw** [comment]
Thanks...With only one 1080, maybe I need 10 days to calculate optical flow..

**Comment by yjxiong** [comment]
The algorithm works well without optical flow. You can also use RGB diff in TSN for speed. This is not a big problem.

**Comment by wzmsltw** [comment]
Okay~ Thanks so much for your advise.

**Comment by caffecoffee** [comment]
Hi @yjxiong @wzmsltw 
I encounter a problem about the calculation time when calculating optical flow in full activity net 1.3. Maybe it will spend 40 days with 8 V100 in cuda10.0 and opencv 4.1. It is said that the version of cuda and opencv is very import. I am curious about your configuration.
Any suggestion is welcome, I'm really confused!
