### ISSUE TITLE
Performance of THUMOS‘14 IoU = 0.6,0.7

### ISSUE THREAD

**Issue by bityangke** [yjxiong/action-detection#10]
Hi Yuanjun,
We want to cite your paper in our work, but we need the mAP of THUMOS14 when IoU = 0.6 and 0.7 , which is not provided in your paper.
Do you have the results at hand for this setting?
Thanks!

**Comment by gss-ucas** [comment]
@bityangke Hi, you will get answer by testing SSN model.

**Comment by yjxiong** [comment]
@bityangke 
You can find the results on the [SSN project website](http://yjxiong.me/others/ssn/#exp).

**Comment by bityangke** [comment]
@yjxiong Thanks very much!
