### ISSUE TITLE
How to generate the proposal list on my own videos?

### ISSUE THREAD

**Issue by realgxf** [yjxiong/action-detection#100]
I want use my own videos, but I don't know how to generate the normalized proposal list. Can you give me some help? Thank you!

**Comment by hubeihubei** [comment]
hello,do you finally run the model on your videos?I also don't know how to generate the normalized proposal list

**Comment by yjxiong** [comment]
Please see the [MMAction](https://github.com/open-mmlab/mmaction) package for the full set of tools.
