### ISSUE TITLE
custom videos

### ISSUE THREAD

**Issue by xianguo-dev** [yjxiong/action-detection#104]
How to use SSN to train and test custom videos？Should I just change the datasets （like activitynet）by my own videos ？If that‘s ok，what else should I do cause some scripts you‘v uploaded is designed for some public datasets.

example：”bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER”→put custom videos into SRC_FOLDER.Will it work？

**Comment by yjxiong** [comment]
It will work. I would recommend you start transferring to the MMAction package. It contains implementation of most state of the art action understanding models and detailed guidance on how to use custom datasets.

**Comment by xianguo-dev** [comment]
Thanks for your kindness.I raised another problem in MMaction，would u plz check it？

**Comment by pzhren** [comment]
> How to use SSN to train and test custom videos？Should I just change the datasets （like activitynet）by my own videos ？If that‘s ok，what else should I do cause some scripts you‘v uploaded is designed for some public datasets.
> 
> 如何使用 SSN 来训练和测试自定义视频？我应该仅仅通过我自己的视频更改数据集(如 activitynet)吗？如果可以的话，我还应该做什么，因为你上传的一些脚本是为一些公共数据集设计的。
> 
> example：”bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER”→put custom videos into SRC_FOLDER.Will it work？
> 
> 例如: “ bash 脚本/提取 _ optical _ flow. sh SRC _ folder OUT _ folder _ worker”→将自定义视频放入 SRC _ folder. 它能工作
我想知道你在使用TAG生成proposals时使用的是rgb还是flow呢？期待您的回复
