### ISSUE TITLE
How to generate my own *_normalized_proposal_list.txt which needed by gen_proposal_list.py in the first step? ?

### ISSUE THREAD

**Issue by quanh1990** [yjxiong/action-detection#106]
Thanks for your great work

**Comment by xianguo-dev** [comment]
Have you generated yet?

**Comment by CrystalGuo0312** [comment]
Have the same question. Could you pls tell us  how to generate my own  *_normalized_proposal_list.txt? Thanks a lot.

**Comment by quanh1990** [comment]
> Have you generated yet?

not yet

**Comment by yjxiong** [comment]
see
https://github.com/yjxiong/action-detection#generating-tag-proposals

**Comment by pzhren** [comment]
> see
> https://github.com/yjxiong/action-detection#generating-tag-proposals

感谢您的分享，我想知道’Generating TAG proposals‘中的ACTIONNESS_RESULT_PICKLE在’Obtaining actionness score‘中生成的时候，它使用的是rgb还是flow呢，期待您的回复
