### ISSUE TITLE
Could you pls tell us how to generate my own *_normalized_proposal_list.txt which needed by gen_proposal_list.py in the first step? ?

### ISSUE THREAD

**Issue by CrystalGuo0312** [yjxiong/action-detection#109]

**Comment by yjxiong** [comment]
See

https://github.com/yjxiong/action-detection#generating-tag-proposals

**Comment by mrlihellohorld** [comment]
> See
> 
> https://github.com/yjxiong/action-detection#generating-tag-proposals

thanks!!!

**Comment by pzhren** [comment]
> See
> 
> 看
> 
> https://github.com/yjxiong/action-detection#generating-tag-proposals

感谢您的分享。我想知道在Read.md中介绍的Generating TAG proposals生成的data/thumos14_tag_test_proposal_list.txt还需要再做Prepare the Proposal Lists这个吗。
因为我注意到Prepare the Proposal Lists这一步是：thumos14_tag_test_normalized_proposal_list.txt
--》thumos14_tag_test_proposal_list.txt，而gen_bottom_up_proposals.py生成的就是data/thumos14_tag_val_proposal_list.txt
