### ISSUE TITLE
when will you release the code of "A pursuit of temporal accuracy in general activity detection "

### ISSUE THREAD

**Issue by wangwen1995** [yjxiong/action-detection#11]
Hi,thanks for your reading!
I have read your paper of "A pursuit of temporal accuracy ...",i found the method of TAG  is useful for my work,could you please release the code?
Thank you so much ~
Looking forward to your replay~

**Comment by yjxiong** [comment]
This unpublished paper is the ``stage-wise training`` part of the SSN paper, which we released earlier. Instead, you refer to and cite the SSN paper.

**Comment by wangwen1995** [comment]
thank you so much !
Looking forward to the release of the TAG code.
