### ISSUE TITLE
Pretrained flow model

### ISSUE THREAD

**Issue by bfshi** [yjxiong/action-detection#111]
Hi, thanks for sharing the code! 

I noticed that the pretrained rgb and flow models (bninception) you provided are different, so could you tell me what is difference?

Because I'm trying to use Resnet as backbone. When I use the torchvision pretrained Resnet on rgb, the performance seems fine. But if I use the same pretrained model on flow, it comes out really terrible. Could you give me some advice on where to find a pretrained Resnet for flow modality? 

Thanks!

**Comment by yjxiong** [comment]
I don't think TorchVision provide optical flow pretrained models. One needs to train them on action recognition datasets.
