### ISSUE TITLE
problem of detection result

### ISSUE THREAD

**Issue by gss-ucas** [yjxiong/action-detection#12]
Hi, @yjxiong when I use your pretrained model to test, my result is worse than paper as follows：

+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.5606 | 0.5084 | 0.4379 | 0.3422 | 0.2466 | 0.1589 | 0.0926 | 0.0399 | 0.0052 | 0.2658  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+

Do you know why please？

**Comment by yjxiong** [comment]
On what dataset, what modality used and which model architecture?

**Comment by gss-ucas** [comment]
@yjxiong oh, sorry, I didn't describe it clearly.
I test model on thumos14 with RGB and Flow modality, and make 'use_reference=True'.

**Comment by yjxiong** [comment]
Would you please paste your testing commands and list the single modality results? It will then be easier to see what’s the problem.

**Comment by gss-ucas** [comment]
@yjxiong Also, python 2.7 may have problem when running 'ctx = multiprocessing.get_context('spawn')', and I have only a gpu device, so I modified code to not use multiprocessing. 
Does it may be the reason? I think not probably.

**Comment by gss-ucas** [comment]
My testing command is: python  ssn_test.py  thumos14  RGB  ./scores/score_thumos14_rgb.npz, and I make 'use_reference=True' in ssn_test.py.
The RGB modality result is:
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4514 | 0.4040 | 0.3447 | 0.2560 | 0.1814 | 0.1128 | 0.0659 | 0.0265 | 0.0060 | 0.2054  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+

The Flow modality result is:
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4108 | 0.3605 | 0.3044 | 0.2420 | 0.1759 | 0.1142 | 0.0634 | 0.0224 | 0.0027 | 0.1885  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+

My evaluation command is: python  eval_detection_results.py  thumos14 ./scores/score_thumos14_rgb.npz  ./scores/score_thumos14_flow.npz

**Comment by yjxiong** [comment]
The flow results look odd. I am checking the reference models.

**Comment by bityangke** [comment]
I am also very concerned about this problem，although I did not run the test code.
I have done some work on action detection, optical flow model's performance seems always a little bit lower than rgb model.

**Comment by yjxiong** [comment]
@bityangke

This issue has nothing to do with how the flow modality performs in detection. It is just that there might be some problem in reproducing the results. 

For well captured videos, like those in THUMOS and UCF101, flow models usually achieve better performance.

**Comment by bityangke** [comment]
Thanks very much for explaining this.

**Comment by gss-ucas** [comment]
@yjxiong Thank you for helping me! I'm looking forward to receiving your response.

**Comment by yjxiong** [comment]
@gss-ucas 

I retried using the following commands on our machine

```
python ssn_test.py thumos14 RGB None ./rep_bninception_thumos14_imagenet_rgb_2.scores.npz  --use_reference
```

to test the reference flow model. It achieves the following performance, which is the same as listed in the README
```
| IoU thresh | 0.10      | 0.20     | 0.30     | 0.40     | 0.50      | 0.60    | 0.70    | 0.80  | 0.90   | Average |
| mean AP    | 0.4561 | 0.4179 | 0.3635 | 0.2953 | 0.2250 | 0.1551 | 0.0943 | 0.0388 | 0.0061 |0.2280  |
```

My rerunning RGB results are almost the same as yours. So I guess there might be some problem with the flow frames you extracted. Can you confirm that you used the provided denseflow tool and followed the instructions in TSN's README?

Also, here are my software version numbers for your references.
```
Python: 3.6.1
PyTorch version:  '0.2.0+4fc54af' (reported by "torch.__version__")
```

**Comment by gss-ucas** [comment]
@yjxiong yes, I think I have extracted optical flow correctly. When I use optical flow extracted from UCF101 to test TSN model, I get similar result as paper. Do you have any another suggestion please?
 I will check it again also.

**Comment by yjxiong** [comment]
Right now I can not think of an instant suggestion. The reasonable RGB results you get mean that the data loading and the testing modules are working properly. Perhaps you can try to see if there is any visible difference of the extracted flow between UCF101 and THUMOS.

**Comment by gss-ucas** [comment]
@yjxiong I extracted optical flow again and then tested flow model, the result is still worse. I saw the following requirement in TSN repo:
![image](https://user-images.githubusercontent.com/31126075/32217566-5966e22a-be63-11e7-9e2e-8a788555bd7a.png)
The requirement said num_works must larger than 1, but I have only one gpu, I set num_workers=1, does it matter？

**Comment by gss-ucas** [comment]
@yjxiong this is my proposal list.
[thumos14_tag_test_proposal_list.txt](https://github.com/yjxiong/action-detection/files/1430256/thumos14_tag_test_proposal_list.txt)

**Comment by gss-ucas** [comment]
@yjxiong The worse result does due to my extracted flow, thanks for your suggestion. I close this issue.

**Comment by bityangke** [comment]
@gss-ucas Hi，Could you tell me about what is the problem with your optical flow.
I guess that I might have the same problem as you.
Thanks!

**Comment by coolbay** [comment]
> @bityangke I use dense flow for opencv3.1 to extract optical flow, which get different result with opencv2. Please see [https://github.com/yjxiong/temporal-segment-networks/issues/152](url) if you have interest.

You mean which one gives you better results, opencv3.1 or opencv2?

**Comment by vivva** [comment]
Hello !  I want to know how to download 213 test videos. Or can you share it with me? Thanke you very much!
