### ISSUE TITLE
issue about the annotation(start frame and ending frame）calculation

### ISSUE THREAD

**Issue by suhaisheng** [yjxiong/action-detection#14]
hello,another question plz...
I wonder how you calculate the start frame and end frame of each groundtruth instance given the start time and end time by thumos14 dataset.
for example,in the video_test_0000004, the start and end time is 0.2 and 1.1 etc. . I multipy it by 30(frame rate) respectively.But the result(
6 | 33
342 | 366
558 | 624
849 | 891
30 | 45
624 | 669
909 | 951
)
 is different from yours(
4 32
340 364
555 621
845 887
29 44
621 666
905 947
),so i want to know  how you calculate it~thx very much!

**Comment by yjxiong** [comment]
We first normalize the start and end time to 0~1 proportional to the total duration of the video and get the start and end frame. The rationale behind this approach is that decoders on different machines tend to extract different numbers of frames even for the same video labeled "30FPS". If you like you can surely use your way of calculation, which may differ for few frames.
