### ISSUE TITLE
Problem about recall performance of TAG

### ISSUE THREAD

**Issue by wzmsltw** [yjxiong/action-detection#15]
Hi Yuanjun,

I generate proposal list of THUMOS14 using "gen_proposal_list.py"  and got "thumos14_tag_test_proposal_list.txt". Then I use evaluation codes in   https://github.com/escorciav/daps/wiki/FAQs , where random score is used for proposals retrieving.

However, I only got AR 39.14% ( AR is calculated with [0.5:0.05:1.0] ), which is lower than 48.9% in SSN paper.
And using this evaluation code, the performance of following method is (with 200 proposals)
DAPs: 33.96%
TAP( sparseprop): 23.13%
SCNN-prop: 37.01% (for performance of scnn-prop, I guess you need to read this: https://github.com/escorciav/daps/wiki )

So how did you evaluate these models? And how can I re-produce TAG performance reported in SSN paper? Thanks!

**Comment by yjxiong** [comment]
Thanks for the info on the SCNN-prop performance, we can update it in Arxiv version of the SSN paper. 
The difference I can think of is we did not do any ranking/retrieval but used all the proposals generated by TAG to evaluate the AR.

**Comment by wzmsltw** [comment]
Hi Yuanjun, I also evaluate the performance using all TAG proposals. 
It got 41.99% AR [0.5:0.05:0.1] , 46.2% AR [0.5:0.05:0.95] .  with totally 250 AN  
However,this performance is still lower than performance reported in SSN.
So can you upload the proposal file you evaluate in https://github.com/escorciav/daps/wiki/FAQs

**Comment by yjxiong** [comment]
We reported the AR evaluated on 0.5:0.05:0.95. The evaluation code will be included in the TAG release of the SSN codebase, which is coming soon. But I think for now it is reasonable to report the number you get from your evaluation pipeline.

**Comment by wzmsltw** [comment]
Ok. Thanks for your help.
