### ISSUE TITLE
probelm of overlapped and unseen THUMOS14 categories

### ISSUE THREAD

**Issue by wzmsltw** [yjxiong/action-detection#16]
Hi Yuanjun,

I also want to evaluate the generaliability of our new proposal method as Table 2. in "A Pursuit of Temporal Accuracy in General Activity Detection". But I am not sure about which 10 classes are overlapped in THUMOS14. Can you list these classes? Thanks.

**Comment by yjxiong** [comment]
Overlapping classes:
```
'CleanAndJerk', 'ThrowDiscus', 'HammerThrow', 'HighJump', 'JavelinThrow', 'LongJump',  'PoleVault', 'Shotput', 'VolleyballSpiking', 'TennisSwing'
```

Non-overlapping classes.
```
'BaseballPitch', 'BasketballDunk', 'Billiards', 'CliffDiving', 'CricketBowling', 'CricketShot', 'Diving', 'FrisbeeCatch', 'GolfSwing', 'SoccerPenalty'
```

You can get them by looking at the classes of these two datasets.

**Comment by wzmsltw** [comment]
Thanks!
