### ISSUE TITLE
Binary actioness classifier training in TAG

### ISSUE THREAD

**Issue by Tonyfy** [yjxiong/action-detection#17]
Hi, @yjxiong 

Would you release your actioness classifier network arch?
When i train the Binary actioness  classifier, It's difficult to converge on big dataset(just over 20W extracted frame) with some simple CNN arch.  RGB modality and flow modality suffer similar problem.

The method of organising train dataset as below:
Positive : frames in all ActivityNet1.3 action instance, sampling interval set to 6, then random choosing some frames.
Negative : frames in all ActivityNet1.3 backgroud , sampling interval set to 6, then random choosing some frames.

Is there any problem in dataset organising ? Should I use all Positive/Negative frames?

thanks a lot.

**Comment by yjxiong** [comment]
Binary classifiers are trained with TSN. Single frame sample is hard to converge.

We will release the proposal generation part soon. Stay tuned.

**Comment by bityangke** [comment]
Yes, single frame model TAG's performance is poor.
Maybe 3 or 5 frames model works OK.

**Comment by HYPJUDY** [comment]
Hi @bityangke , what did you mean by "3 or 5 frames model". Can you share your method or code in training binary actioness classifier?

**Comment by bityangke** [comment]
@HYPJUDY  TSN model takes multiple frames as input.
If you train TAG model use single frame CNN, you are not using TSN.

**Comment by bityangke** [comment]
@HYPJUDY  Sorry but I have not trained TSN-TAG. 
May I have your contact information? I want to ask you some question about the internship.

**Comment by HYPJUDY** [comment]
@bityangke Thanks. You can find my email in my GitHub page.

**Comment by bityangke** [comment]
@HYPJUDY Hi, I have sent you an e-mail in Chinese. Sorry for the delay.

**Comment by Tonyfy** [comment]
@yjxiong @bityangke @HYPJUDY 
Thank a lot.

**Comment by adwardlee** [comment]
@Tonyfy Hi, did you get good actioness classifier by training with all the rgb and optical flow frames in the snippet?

**Comment by mangdian** [comment]
@Tonyfy @adwardlee  Have you succeed in training a good action classifier based on TAG?

**Comment by mangdian** [comment]
@yjxiong I am trying to use TSN to train a binary action classifier. I use the default parameter seting of tsn-pytorch. But I found that the network don't converge neither with RGB input or optical flow input? How come? Or the parameters setting should be changed?

**Comment by kstys** [comment]
hello,everyone.
I come cross a trouble that I can't solve it.so(I am a green hand using pytorch) ,I hope your help,thanks a lot.

when i load the module parameter ,and it will say:
RuntimeError: While copying the parameter named inception_5a_3x3_reduce_bn.running_mean, whose dimensions in the model are torch.Size([192]) and whose dimensions in the checkpoint are torch.Size([1, 192]).
and then I want to modify the model to adapt it ,but how to do it ? or you have the other method to do with it?? @Tonyfy @bityangke @HYPJUDY @adwardlee

**Comment by yjxiong** [comment]
We released the TAG proposal code. Now you can run your own proposal models to get proposals for any dataset.
