### ISSUE TITLE
How to run ssn on custom videos

### ISSUE THREAD

**Issue by vra** [yjxiong/action-detection#18]
Hi @yjxiong ,
Thanks for your cool work, it's really useful. I wonder how to run ssn action detection on custom videos(which are not included in ActvityNet and Thumos) using pretrained model, can you give me some hints? Thank you in advance.

**Comment by vikashch** [comment]
+1

**Comment by Tonyfy** [comment]
Maybe some step as follow:
1 load a video, extract all frames with a interval of 6 
2 compute optical flow on these frames
3 use TAG algorithm get temporal action proposals
4 process each proposal using TSN network
5 save all detect result(such as in json file), then re-edit the test video with the detect result to get a visualizing demo.

**Comment by jiaozizhao** [comment]
Hi @Tonyfy ,

Could you explain what ´s the meaning of each line in the file thumos14_tag_test_normalized_proposal_list.txt. How can we get the file for our own videos? Thanks.

**Comment by yjxiong** [comment]
https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files

**Comment by jiaozizhao** [comment]
Hi, @yjxiong. Thank you very much. I just try to test a few videos in thumos14. But the result is very weird. I only got a file called ´result´ with one line like ¨ <80>^D<95>^C^@^@^@^@^@^@^@}<94>¨ after I run python ssn_test.py thumos14 RGB none result_inceptionv3_thumos14_imagenet_rgb.npz --arch InceptionV3 --use_reference. I don´t think my result is correct. Could you tell me what the result should be like? The scores are stored in the file ¨result¨?

**Comment by kstys** [comment]
hello.
I come cross a trouble that I can't solve it.so(I am a green hand using pytorch) ,I hope your help,thanks a lot.

when i load the module parameter ,and it will say:
RuntimeError: While copying the parameter named inception_5a_3x3_reduce_bn.running_mean, whose dimensions in the model are torch.Size([192]) and whose dimensions in the checkpoint are torch.Size([1, 192]).
and then I want to modify the model to adapt it ,but how to do it ? or you have the other method to do with it?? @vra @vikashch @Tonyfy @jiaozizhao

**Comment by yjxiong** [comment]
We released the TAG proposal code. Now you can run your own proposal models to get proposals for any video.

**Comment by SHaiHosh** [comment]
Hi @yjxiong 
Thank you for this great work
I'm trying to find a way to use my own video (i.e. video not from any dataset)
I understand that "TAG proposal code" can help me with this
But I don't find this code 
can you point me to the file?

**Comment by yjxiong** [comment]
@SHaiHosh 
You can find the instructions here

https://github.com/yjxiong/action-detection#train-tag-models

**Comment by SHaiHosh** [comment]
I meant that I want to evaluate my own video which does not appear in the THUMOS14/activitynet list. Just to upload a movie and get it trimmed (and the trimmed sections classified)
You referred me to the training section
Am I missing something?

**Comment by yjxiong** [comment]
@SHaiHosh You are not missing anything. That part contains the instruction for running TAG proposal generation.

**Comment by SHaiHosh** [comment]
@yjxiong 
I see that I have to run the testing and validation for generation of series of sliding-window proposals on THUMOS14
Only then I can train a binary actionness classifier
Then I should be able to split the video into actions (which is my goal)

My question is: Do I really have to go over all this process in order to be able to split my video?

**Comment by yjxiong** [comment]
@SHaiHosh 

You can use the pretrained actionness classifier here https://github.com/yjxiong/action-detection/blob/master/README.md#obtaining-actionness-score

**Comment by intheroom** [comment]
I wonder will video's fps affect how we config interval. For example, if we extract frames with an interval of 6 on a 30fps video we will get more frames than if we extract optical flow on 10fps one. So my question is what the standard fps of the input video is?

**Comment by mrlihellohorld** [comment]
> Hi @Tonyfy ,
> 
> Could you explain what ´s the meaning of each line in the file thumos14_tag_test_normalized_proposal_list.txt. How can we get the file for our own videos? Thanks.

Hi, have u resolved the problem?
