### ISSUE TITLE
ssn_train.py

### ISSUE THREAD

**Issue by jzxww** [yjxiong/action-detection#20]
when I run： python ssn_train.py thumos14 RGB -b 16 --lr_steps 20 40 --epochs 45
something wrong,i donot know why ?nobody else have met this issue?
  File "ssn_train.py", line 103
  modality=args.modality, exclude_empty=True, **sampling_configs,
                                                                                                     ^

SyntaxError: invalid syntax

**Comment by Alvin-Zeng** [comment]
Hello, jzxww. I met the same problem as yours. Could please tell me how did you resolve this problem?

**Comment by jzxww** [comment]
have you got the right txt file of train_proposal_list and test_proposal_list

**Comment by Alvin-Zeng** [comment]
I found it is caused by the incompatibility between python 2 and python 3 and there are two ways to resolve this one.
1、change your python version from python 2 to python 3
2、move '**sampling_configs' to the last position of all arguments. (shown below)

` SSNDataSet("", val_prop_file,
                   new_length=data_length,
                   modality=args.modality, exclude_empty=True, 
                   aug_seg=args.num_aug_segments, body_seg=args.num_body_segments,
                   image_tmpl="img_{:05d}.jpg" if args.modality in ["RGB", "RGBDiff"] else args.flow_prefix+"{}_{:05d}.jpg",
                   random_shift=False,
                   transform=torchvision.transforms.Compose([
                       GroupScale(int(scale_size)),
                       GroupCenterCrop(crop_size),
                       Stack(roll=(args.arch in ['BNInception', 'InceptionV3'])),
                       ToTorchFormatTensor(div=(args.arch not in ['BNInception', 'InceptionV3'])),
                       normalize,
                   ]), reg_stats=train_loader.dataset.stats,**sampling_configs,)`

**Comment by Alvin-Zeng** [comment]
I found it is caused by the incompatibility between python 2 and python 3 and there are two ways to resolve this one.
1、change your python version from python 2 to python 3
2、move '**sampling_configs' to the last position of all arguments. (shown below)
```python
SSNDataSet("", val_prop_file, 
                    new_length=data_length, 
                    modality=args.modality, exclude_empty=True, 
                    aug_seg=args.num_aug_segments, body_seg=args.num_body_segments, 
                    image_tmpl="img_{:05d}.jpg" if args.modality in  ["RGB", "RGBDiff"] else args.flow_prefix+"{}_{:05d}.jpg", random_shift=False, 
                   transform=torchvision.transforms.Compose([ 
                                 GroupScale(int(scale_size)), 
                                 GroupCenterCrop(crop_size), 
                                 Stack(roll=(args.arch in ['BNInception', 'InceptionV3'])), ToTorchFormatTensor(div=(args.arch not in ['BNInception', 'InceptionV3'])), normalize, ]), 
                                reg_stats=train_loader.dataset.stats,
                                **sampling_configs)
```

**Comment by yjxiong** [comment]
This codebase is written with Python3. I suggest using Python3 to avoid this problem.
