### ISSUE TITLE
how to get best_iou and overlap_self value in thumos14_tag_val_normalized_proposal_list.txt

### ISSUE THREAD

**Issue by cc786537662** [yjxiong/action-detection#24]
hello   @yjxiong ，i am trying to reimplement your TAG  method，for now i can get actionness score and do the grouping scheme，and after the NMS，i can get 82 proposals for video_validation_0000201.mp4, and
i want to replace the proposals in your thumos14_tag_val_normalized_proposal_list.txt with mine to check if my reimplement  is all right , but yout TXT file not only contain the proposal itself,but also the best_iou and overlap_self items to calculate the incomplete proposal as well as the background proposal , but i wonder how to calculate these two items,because there is no description in your paper about it.

e.g: thumos14_tag_val_normalized_proposal_list.txt
# 59
video_validation_0000201
1
1
1
8 0.8631 0.8926
32
8 0.7603 0.8995 0.8684 0.8956
8 0.6497 0.6497 0.8593 0.9047
0 0.0000 0.0000 0.1354 0.1626
##format
(label,best_iou,overlap_self,start_frame_norm,end_frame_norm)

THANK YOU .

**Comment by yjxiong** [comment]
Best IOU is the maximal IOU of one proposal against any groudtruth instance. Best overlap is the maximal `overlap_duration/proposal_duration`, repectively. This is described in the paper on how to generate input for the two classifiers (Activity & Completeness) in SSN.

**Comment by cc786537662** [comment]
thank you,I got that part now!
