### ISSUE TITLE
What's the size of extracted frames and optical flow images?

### ISSUE THREAD

**Issue by HYPJUDY** [yjxiong/action-detection#27]
The authors suggest using the tools provided in the TSN repo to extract frames and optical flow images. I wonder should I resize the images the same way as TSN repo? What's the image size the authors used?
One dataset used in TSN repo is UCF101. The original videos' size is 320\*256. The command in TSN repo resize images to 340\*256 as follows,
```
python tools/build_of.py ${SRC_FOLDER} ${OUT_FOLDER} --num_worker ${NUM_WORKER} --new_width 340 --new_height 256 2>local/errors.log
```
And in the \*_train_val.prototxt the `crop_size` is 224.
The size of THUMOS14 videos is 320\*180, in resnet/vgg/BNInception models `input_size = 224`, in InceptionV3/inception models `input_size = 299`.

I got worse results when I used reference models to evaluate my extracted images, which haven't been resized (320\*180). (The image number is the same as the image number of denseflow extracted images)
```
action-detection$ python3 ssn_test.py thumos14 RGB none score_thumos14_rgb_reference.npz --use_reference
action-detection$ python3 eval_detection_results.py thumos14 score_thumos14_rgb_reference.npz

rgb reference model
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4375 | 0.3839 | 0.3266 | 0.2430 | 0.1639 | 0.1051 | 0.0588 | 0.0244 | 0.0059 | 0.1943  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+


action-detection$ python3 ssn_test.py thumos14 Flow none score_thumos14_flow_reference.npz --use_reference
action-detection$ python3 eval_detection_results.py thumos14 score_thumos14_flow_reference.npz

+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4166 | 0.3769 | 0.3183 | 0.2538 | 0.1907 | 0.1208 | 0.0698 | 0.0250 | 0.0045 | 0.1974  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
```

**Comment by bityangke** [comment]
You need to resize images to the size required before crop

**Comment by HYPJUDY** [comment]
Resize to 340*256?

**Comment by bityangke** [comment]
@HYPJUDY  Yes for BN-Inception

**Comment by cc786537662** [comment]
@HYPJUDY I just resize all images to 340*256 by using --new_width 340 --new_height 256,and both the RGB and Flow evaluation result looks as good as the SSN paper says,
in your case，did you use opencv2？ because the author‘s denseflow extraction program works fine only under opencv2 , not opencv3. 
BTW  ,my environment for  extracted frames and optical flow  is python2.7+opencv2

**Comment by HYPJUDY** [comment]
Thanks, that works.
