### ISSUE TITLE
Proposal list

### ISSUE THREAD

**Issue by jzxww** [yjxiong/action-detection#28]
Hi, in your proposal_list.txt,what does each line stand for?
something like below:
# 1
video_validation_0000354
1
1
0
226
0 0.0000 0.0000 0.7439 0.7713
0 0.0000 0.0000 0.7533 0.7698
0 0.0000 0.0000 0.7259 0.7682
0 0.0000 0.0000 0.7125 0.7698
0 0.0000 0.0000 0.7408 0.7737
0 0.0000 0.0000 0.7408 0.7792
 
How can I get the proposal list like this ?can you release the code to produce the proposal list? Thank you so much! Looking forward to your reply~

**Comment by yjxiong** [comment]
Please read this

https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files
