### ISSUE TITLE
Window scales for sliding window

### ISSUE THREAD

**Issue by lyttonhao** [yjxiong/action-detection#3]
Hi, I just read your papers and notice that the method can also achieve good performance with proposals generated by sliding windows. In your paper, "we generate windows in 20 exponential scales starting from 0.3 second long". Could you provide the details of 20 scales? Thanks a lot!

**Comment by yjxiong** [comment]
exponential scales simply refer to `0.3 ** 2**s, s=0, ..., 19`.
