### ISSUE TITLE
proposal generation code

### ISSUE THREAD

**Issue by mangdian** [yjxiong/action-detection#30]
would you please release the code for training binary classifier based on TAG and generating proposals by 
watershed algorithm?

**Comment by haofanwang** [comment]
+1

**Comment by Rizhiy** [comment]
+1

**Comment by mangdian** [comment]
+1

**Comment by wangwen39** [comment]
+1

**Comment by mangdian** [comment]
@yjxiong Still going to release proposal generation code?

**Comment by jxiangli** [comment]
+1

**Comment by Yanchunswallow** [comment]
+1

**Comment by kstys** [comment]
hello,everyone.
I come cross a trouble that I can't solve it.so(I am a green hand using pytorch) ,I hope your help,thanks a lot.

when i load the module parameter ,and it will say:
RuntimeError: While copying the parameter named inception_5a_3x3_reduce_bn.running_mean, whose dimensions in the model are torch.Size([192]) and whose dimensions in the checkpoint are torch.Size([1, 192]).
and then I want to modify the model to adapt it ,but how to do it ? or you have the other method to do with it?? @mangdian @haofanwang @ @Rizhiy @wangwen39 @jxiangli

**Comment by Rizhiy** [comment]
@kstys as the error says, dimensions of tensors you want to copy do not match.
Either `squeeze` the bigger one (size[1, 192]) or `unsqueeze` the smaller one (size[192]).

**Comment by Rizhiy** [comment]
@kstys I would need to see more of the code to help you out at this point. It's also better to move this discussion somewhere else since it's not related to the original issue. Send me a link/code snippet.

**Comment by kstys** [comment]
thanks a lot,I have move the question to **model not match** 
https://github.com/yjxiong/action-detection/issues/48
I am sorry to discuss the question in the topic. @Rizhiy

**Comment by zhangzhizz** [comment]
+1

**Comment by yjxiong** [comment]
We released the TAG proposal code. Now you can run your own proposal models to get proposals for any dataset.
