### ISSUE TITLE
About proposal list (no CliffDiving class in val list, missing video_test_0001496 in test list)

### ISSUE THREAD

**Issue by HYPJUDY** [yjxiong/action-detection#31]
1. Why all validation proposals (used for training) you generated for CliffDiving class videos are labelled with 8 (Diving) but not 5 (CliffDiving)? Wouldn't this deteriorate the performance of CliffDiving classifier?
For example, in `thumos14_tag_val_normalized_proposal_list.txt`
```
# 380
video_validation_0000161
1
1
8
8 0.1826 0.2280
8 0.3393 0.3863
8 0.4268 0.4754
8 0.8228 0.8957
5 0.1826 0.2280
5 0.3393 0.3863
5 0.4268 0.4754
5 0.8228 0.8957
86
8 0.3272 0.3438 0.3458 0.4689
8 0.1725 0.1725 0.1972 0.4689
8 0.2917 0.3254 0.3522 0.4625
8 0.2999 0.2999 0.3139 0.4754
8 0.1530 0.1530 0.1777 0.4949
8 0.2458 0.2458 0.2977 0.4949
8 0.7752 0.8887 0.3458 0.3911
8 0.7883 0.8401 0.3425 0.3944
8 0.8001 0.8023 0.3393 0.3976
8 0.7602 0.9535 0.3490 0.3879
......
```

2. `thumos14_tag_test_normalized_proposal_list.txt` has **200** videos while there are **213** videos in `TH14_Temporal_Annotations_Test\xgtf_renamed`. Two reasonable missing videos are `video_test_0000270` (its annotationa are HammerThrow but its ground truth in video is HairCut which doesn't belong to the 20 classes) and `video_test_0001292` (it only has ambiguous annotations).
It seems that another missing video `video_test_0001496` can be included into test list after modifying the annotations (annotations are CricketShot while ground truth is FrisbeeCatch).

**Comment by bityangke** [comment]
You will find that all cliffdiving instances also belong to diving category in thumos dataset.

**Comment by yjxiong** [comment]
1. We will look at the data.
2. Their annotation seems to be longer than the duration of the videos. It is better to leave them out.
