### ISSUE TITLE
details about the temporal actionness grouping?

### ISSUE THREAD

**Issue by adwardlee** [yjxiong/action-detection#33]
Hi @yjxiong , 
  Could you please tell me about the details about the temporal actionness grouping if possible? What is the duration of each snippet and how many RGB frames and optical flow frames are sampled from each snippet? Thanks.

**Comment by adwardlee** [comment]
Hi @yjxiong ,
When sampling the frames, the fps is 1 or the default of video? Thanks.

**Comment by yjxiong** [comment]
We extract video frames at its original framerate. Other details can be found in the SSN paper.
