### ISSUE TITLE
problems about proposal file

### ISSUE THREAD

**Issue by mangdian** [yjxiong/action-detection#34]
![f0ayo rt 4pe3ny_sv07r q](https://user-images.githubusercontent.com/18326098/35227493-3fb5ae86-ffc9-11e7-83a1-2a7366777319.png)

what are these zeros mean?

**Comment by mangdian** [comment]
in thumos14_tag_val_normalized_proposal_list.txt, there are many videos with no groundtruth?

**Comment by yjxiong** [comment]
Please read this
https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files

**Comment by mangdian** [comment]
NUM_GT number of ground truth action instances in this video. This number can be set to 0 for testing videos where we do not have annotations.

**Comment by mangdian** [comment]
I read the wiki, I understand that testing videos have no annotations so that the number of ground truth shall be zero. But why does the proposal of some training videos(validation videos in Thumos14) contains no grountruth?

**Comment by yjxiong** [comment]
You are seeing the annotation file of the whole THUMOS14 dataset, which has 101 classes. Among them, there are only 20 action classes with annotations. Videos without annotation are not used in either training nor testing.

**Comment by mangdian** [comment]
I got it! Thank you so much!!!
