### ISSUE TITLE
Flow + RGB result

### ISSUE THREAD

**Issue by Rizhiy** [yjxiong/action-detection#40]
Are the results reported for 'Flow + RGB' come from 2 model ensemble?

**Comment by yjxiong** [comment]
It's by fusing the output of Flow and RGB models (two-stream).

**Comment by Rizhiy** [comment]
What do you mean by 'fusing'?

**Comment by yjxiong** [comment]
There is no setting of flow+rgb training. Fusion is averaging the scores of both models for each detection. 
Please refer to the paper for these details.
