### ISSUE TITLE
HDD training speed

### ISSUE THREAD

**Issue by Rizhiy** [yjxiong/action-detection#41]
Hi, I'm trying to train the model.
My data is stored on HDD and the script takes a long time to load data into memory, how can I speed it up?

**Comment by yjxiong** [comment]
I cannot think of many ways to load images faster. The dataset might be too huge for the cache so eventually, the reading speed will decrease to the HDD reading speed.
I would suggest using an SSD instead or Memdisk/Redis if you have a huge RAM.

**Comment by Rizhiy** [comment]
For anyone having the same issue later, it helps to decrease batch size and increasing number of workers.
