### ISSUE TITLE
Incomplete description in wiki

### ISSUE THREAD

**Issue by Rizhiy** [yjxiong/action-detection#42]
On [wiki page about proposal format](https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files) it says:
> **FPS** The next line is for the frames per second (`FPS`) of this video, if the unit is `frame`, then this line will be 1. If the unit is

and ends there.

What should I put for `FPS` if my proposals are normalised?

**Comment by yjxiong** [comment]
You can put 1 here and use 
https://github.com/yjxiong/action-detection/blob/master/gen_proposal_list.py
to translate your normalized proposals to proposals used for training.

See 
https://github.com/yjxiong/action-detection/blob/master/data/thumos14_tag_val_normalized_proposal_list.txt
for example.
