### ISSUE TITLE
Coverage Threshold

### ISSUE THREAD

**Issue by Rizhiy** [yjxiong/action-detection#43]
During dataset creation, `bg_coverage` of the whole video is checked in:
https://github.com/yjxiong/action-detection/blob/4cd92c9c8f48c2e0358624ec5c12b6a38fc1f3a2/ssn_dataset.py#L127-L129

Why is this done? Can I remove this condition?

My videos are very long, with lots of activity. Therefore backgrounds are quite short, therefore most of the proposals fail.

**Comment by yjxiong** [comment]
This is to avoid too short background instances. You can definitely modify the code as you like to fit your needs.
