### ISSUE TITLE
Length and content of videos

### ISSUE THREAD

**Issue by Rizhiy** [yjxiong/action-detection#44]
Is there a guideline to how long the videos should be and how much `activity` they should contain?
e.g. 

- If I have a long video which is mostly background, should I cut the background parts out?
- If I have a long video with lots of activity, should I split it into several short ones? I noticed that there is a number of proposals specified in dataset config:
https://github.com/yjxiong/action-detection/blob/4cd92c9c8f48c2e0358624ec5c12b6a38fc1f3a2/data/dataset_cfg.yaml#L11
Does that mean that only 8 proposals are used per video?

**Comment by yjxiong** [comment]
That parameter controls the number of proposals sampled in each iteration for a video. The algorithm does not make an assumption on how many proposals are there for each video. There is no requirement on the video length nor the number of activities.
