### ISSUE TITLE
Question about sample balance

### ISSUE THREAD

**Issue by mangdian** [yjxiong/action-detection#45]
In your paper, the ratio of positive, background, and incomplete proposals is 1:1:6. So when you train the action classifier, background proposal : foreground proposal is 1:1, but there are 100 class(in activitynet1.2), which means that the sample of foreground of each class is much more less than backgound sample. Should this problem be ignored?  Would it bring some problem?

I tried training SSN model without any modification of your code, and find that after several backward and update operation, the model tends to predict all the proposals as background. How come?

**Comment by mangdian** [comment]
?

**Comment by yjxiong** [comment]
The question is, why is this a problem. The background class cannot be treated as a simple "activity" class so it needs special treatment.

If you run the code correctly you should be able to reproduce the numbers reported.

**Comment by mangdian** [comment]
@yjxiong  I just git clone this repository and run the code without any modification.

**Comment by yjxiong** [comment]
The provide models are trained with this codebas. You may try to run them first. Training using the default setting should also get you the similar performance.

**Comment by mangdian** [comment]
@yjxiong  OK, I'll try again. Would you please release the code of TAG training?
