### ISSUE TITLE
No module model_zoo

### ISSUE THREAD

**Issue by kstys** [yjxiong/action-detection#46]
Hello, @yjxiong 
I train the network with 'ssn_train.py',and then come across the error :import model_zoo,and no module named ' model_zoo' in 'ssn_models.py'

**Comment by kstys** [comment]
I have solved it ,I'm sorry to bother you . @yjxiong

**Comment by 666zcli** [comment]
@kstys hello,  I met the same problem. Could you tell me how to resolve it？
