### ISSUE TITLE
val_proposal_list about THUMOS14

### ISSUE THREAD

**Issue by kstys** [yjxiong/action-detection#47]
Hi,I run the code gen_proposal_list.py, and then get the data about that:

0 0.0000 0.0000 0 0
0 0.0000 0.0000 0 0
13 0.4760 0.4823 0 0
0 0.0000 0.0000 0 0
0 0.0000 0.0000 0 0
0 0.0000 0.0000 0 0
0 0.0000 0.0000 0 0
0 0.0000 0.0000 0 0

in above proposal data,the are many invalid data,is that correct??

**Comment by yjxiong** [comment]
no. you should check whether the video frames are properly located
