### ISSUE TITLE
mdoel size not  match

### ISSUE THREAD

**Issue by kstys** [yjxiong/action-detection#48]
hello ,
I run the code and then come across the problem about size that model size does not match parameter size.  
RuntimeError: While copying the parameter named inception_4d_pool_proj_bn.running_var, whose dimensions in the model are torch.Size([128]) and whose dimensions in the checkpoint are torch.Size([1, 128]).

**Comment by yjxiong** [comment]
First a reminder, ask your questions in a single issue. Don't spam others' issues. 

For your problem, try PyTorch version 0.2.0 and see if is running properly

**Comment by kstys** [comment]
sorry,I'll keep it in mind

**Comment by kstys** [comment]
firstly I run the ssn_test.py code,it will call the class SSN(),and then you can see the function 

> self._prepare_base_model(base_model)
due to it's model is BNInception ,so the code

> self.base_model = getattr(model_zoo, base_model)()
will be carried out ,end then it will call the model_zoo,you will see

> class BNInception(nn.Module):
>     def __init__(self, model_path='model_zoo/bninception/bn_inception.yaml', num_classes=101,
>                        weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
>         super(BNInception, self).__init__()
> 
>         manifest = yaml.load(open(model_path))
> 
>         layers = manifest['layers']
> 
>         self._channel_dict = dict()
> 
>         self._op_list = list()
>         for l in layers:
>             out_var, op, in_var = parse_expr(l['expr'])
>             print('out_var',out_var)
>             print('in_var',in_var)
>             if op != 'Concat':
>                 id, out_name, module, out_channel, in_name = get_basic_layer(l,
>                                                                 3 if len(self._channel_dict) == 0 else self._channel_dict[in_var[0]],
>                                                                     conv_bias=True)
> 
>                 # print('out_name',out_name)
>                 # print('in_name',in_name)
>                 #module is network
>                 self._channel_dict[out_name] = out_channel
>                 self._op_list.append((id, op, out_name, in_name))
>             else:
>                 self._op_list.append((id, op, out_var[0], in_var))
>                 channel = sum([self._channel_dict[x] for x in in_var])
>                 self._channel_dict[out_var[0]] = channel
>         print('self._channel',self._channel_dict)
>         self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))

and then the error will appear.beacause the pytorch function

>  self.load_state_dict() 
will rasie out 
KeyError: 'unexpected key "inception_3c_double_3x3_2_bn.weight" in state_dict' in pytorch 0.2.0,


and yesterday,I install the pytorch 0.3.0 and it will appear the error

RuntimeError: While copying the parameter named inception_4d_pool_proj_bn.running_var, whose dimensions in the model are torch.Size([128]) and whose dimensions in the checkpoint are torch.Size([1, 128]).

I try to solve it ,but failed.

**Comment by zhangzhizz** [comment]
@yjxiong hello i an running the code ,and i meet the same problem : KeyError: 'unexpected key "inception_3c_double_3x3_2_bn.weight" in state_dict,i do not know how to deal with it,could you help me?

**Comment by yjxiong** [comment]
We did not test on pytorch > 0.2
