### ISSUE TITLE
pytorch weight file

### ISSUE THREAD

**Issue by hjeun** [yjxiong/action-detection#50]
I'm trying to run 'ssn_test.py'.

I get the arguments in the example script below, but where can I get TRAINING_CHECKPOINT?

python ssn_test.py DATASET MODALITY TRAINING_CHECKPOINT RESULT_PICKL

There is no way to download 'the trained pytorch weights file' from authors.

**Comment by yjxiong** [comment]
no need to manually download.

See here on how to test the reference models:

https://github.com/yjxiong/action-detection#using-reference-models-for-evaluation
