### ISSUE TITLE
own trained check file dose not contain 'arch', 'best_loss', 'epoch', 'reg_stats' 

### ISSUE THREAD

**Issue by hjeun** [yjxiong/action-detection#51]
I trained the weights using ssn_train.py and got the weight pth.tar file.
But, when I try to test with this weight file, error occured.
The weight file saved by ssn_train.py is not correctly configured for ssn_test requiring 'arch', best_loss', 'epoch', 'reg_stats', 'state_dict' as key in dictionary.
Do I need to manually change configuration of the weight file?
And what is 'reg_stats'?

**Comment by yjxiong** [comment]
I don't feel the file produced by the training script will miss them
https://github.com/yjxiong/action-detection/blob/master/ssn_train.py#L163

Are you sure you are using the right file.

**Comment by hjeun** [comment]
I just found the weight file for the best_loss including them. Thanks.
