### ISSUE TITLE
Extract optical flow and frames

### ISSUE THREAD

**Issue by hjeun** [yjxiong/action-detection#52]
I failed to compile dense flow due to opencv version.
So I tried to extract optical flow on my own by using opencv lib.
Here, I got a question.
Did you extract frames with interval 6 or every frame?
What about optical flow with inverval 6?
What method did you use to compute optical flow? basic TVL1? 
There are some lib for optical flow in opencv.
And does optical flow need to be normalized with range [0,1] for input?

**Comment by hjeun** [comment]
Also, when I run test code with dataset configured by every frame, I got out of memory error.
I set --arch='BNInception', modality='Flow', and test_batch size=1.
The GPU is 1080ti.

**Comment by yjxiong** [comment]
Interval is 6 in most experiments. DenseFlow uses TVL1 flow algorithm. Read the TSN paper on how to process your optical flow.
