### ISSUE TITLE
how can i  use  your model to test

### ISSUE THREAD

**Issue by WestBbbbrook** [yjxiong/action-detection#54]
hello, i have gen_proposal_list  and then i want to test a video.
I do not know how to use your model.
In your yjxiong/tensorflow-model-zoo.torch/   I run the code pytorch_load.py in bninception  and inceptionresnetv2 and inceptionv4   
the error  as follow:

(py2_ten1.6_torch3.1) ct@PowerEdge-T630:~/myfile/project/SSN/action-detection/model_z
oo/inceptionresnetv2$ python pytorch_load.py /home/ct/anaconda2/envs/py3/envs/py2_ten1.6_torch3.1/lib/python2.7/site-packages/h5py
/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "pytorch_load.py", line 521, in <module>
    state_dict = load()
  File "pytorch_load.py", line 376, in load
    load_conv2d(state_dict, name_pth='conv2d_1a', name_tf='Conv2d_1a_3x3')
  File "pytorch_load.py", line 303, in load_conv2d
    h5f = h5py.File('dump/InceptionResnetV2/'+name_tf+'.h5', 'r')
  File "/home/ct/anaconda2/envs/py3/envs/py2_ten1.6_torch3.1/lib/python2.7/site-packa
ges/h5py/_hl/files.py", line 269, in __init__    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ct/anaconda2/envs/py3/envs/py2_ten1.6_torch3.1/lib/python2.7/site-packa
ges/h5py/_hl/files.py", line 99, in make_fid    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'dump/InceptionResnetV2/Con
v2d_1a_3x3.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

could you help me.

**Comment by yjxiong** [comment]
```
Unable to open file (unable to open file: name = 'dump/InceptionResnetV2/Con
v2d_1a_3x3.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
