### ISSUE TITLE
Params of BN layer

### ISSUE THREAD

**Issue by h-bo** [yjxiong/action-detection#55]
I rewrote tsn model by tensorflow. But when reusing the pretrianed model you support, I found the result worse than expected. I found your BN layer might  be a little different from simplily x= (x-mean_x)/var_x*scale + bias. Is that so? If not, can you please have an introduction to your BN layer.
Thanks

**Comment by yjxiong** [comment]
It is exactly the same BN implementation. Please put your issue to the TSN repo. 

One thing you need to notice is how the framework store the BN statistics. This is not specified in the paper.
