### ISSUE TITLE
the test result

### ISSUE THREAD

**Issue by WestBbbbrook** [yjxiong/action-detection#57]
hello,i run your code and the setp just like question #13 ,i just test two video 250 560 and thy both have annotation.i  try extract frame in per-one-frame and per-six-frame .
but the result is : 
+Detection Performance on thumos14+------+------+------+------+------+------+---------+
| IoU thresh | 0.10 | 0.20 | 0.30 | 0.40 | 0.50 | 0.60 | 0.70 | 0.80 | 0.90 | Average |
+------------+------+------+------+------+------+------+------+------+------+---------+
| mean AP    | nan  | nan  | nan  | nan  | nan  | nan  | nan  | nan  | nan  | nan     |
+------------+------+------+------+------+------+------+------+------+------+---------+
i do：
1.>python  build_of.py  SRC  OUT  
whilch structure is SRC/video_test_0000179.mp4    and unzip the flow.zip and img.zip to 
  OUT/video_test_0000250/img_00001.jpg
2.>python gen_proposal_list.py thumos14  OUT
the thumos14_tag_test_proposal_list.txt is like this:

1
src2/video_test_0000560
1501
1
3
2 265 289
2 597 622
2 1046 1076
39
2 0.2274 0.2274 955 1088
2 0.2858 0.2858 555 638
2 0.2779 0.2779 973 1082

3.>python ssn_test.py thumos14 RGB none result_inceptionv3_thumos14_imagenet_rgb.npz --arch InceptionV3 --use_reference
4.>python eval_detection_results.py thumos14 result_inceptionv3_thumos14_imagenet_rgb.npz

should change somewhere else?  wish your reply.

**Comment by vivva** [comment]
Hello !  May I ask if you have solved it? And how can I find the 'humos14 result_inceptionv3_thumos14_imagenet_rgb.npz' ?Thanke you very much!!

**Comment by vivva** [comment]
I can see that you use "python ssn_test.py thumos14 RGB none RESULT_PICKLE --use_reference" to generate "result_inceptionv3_thumos14_imagenet_rgb.npz"！
