### ISSUE TITLE
A question about installing denseflow.

### ISSUE THREAD

**Issue by Syrup274** [yjxiong/action-detection#58]
I tried to install denseflow following the instructions in denseflow homepage. Then I turned to the install method in TSN, but I still faild. Now I delete my opencv in case of the difference in opencv versions. My cuda is 9.0. How can I correctly compile opencv and install denseflow correctly?  Just clone the TSN code of dock branch and run build_all.sh? Will it works?  Thanks very much.

**Comment by yjxiong** [comment]
In case of build issue of TSN, you can use the built docker image of TSN at

https://hub.docker.com/r/bitxiong/tsn/

which has the denseflow built in.

You need NVIDIA-Docker to run it.

**Comment by Syrup274** [comment]
Thanks for your advice.
I feel sorry that I know little about docker, and i really want to build DenseFlow on my own virtual envirnment. 
I found the Dockerfile in the TSN codebase. Can I follow the this file to config my virtualenv and build denseflow in this environment(run build_all.sh with opencv_cuda9.patch)? 
Thanks again.
