### ISSUE TITLE
int type numerator bug

### ISSUE THREAD

**Issue by HYPJUDY** [yjxiong/action-detection#59]
https://github.com/yjxiong/action-detection/blob/c27d52e558690b156a6184e19846d63a87693985/load_binary_score.py#L122

Better to use 
```
self.fg_per_video = int(prop_per_video * (float(fg_ratio) / denum))
self.bg_per_video = int(prop_per_video * (float(bg_ratio) / denum))
```

or change
https://github.com/yjxiong/action-detection/blob/c27d52e558690b156a6184e19846d63a87693985/load_binary_score.py#L88
to
```
prop_per_video=12, fg_ratio=3.0, bg_ratio=9.0, 
```

because in some version of Python, `fg_ratio / denum = 0` when the type of `fg_ratio` is `int`.

**Comment by yjxiong** [comment]
Thanks. We use Python3. It defaults all division to floating points.
