### ISSUE TITLE
How to get temporal region proposals by myself?

### ISSUE THREAD

**Issue by daiqi1989** [yjxiong/action-detection#6]
As it provides the proposal file, I don't need it to reproduce the results. However, I want to know how to train the actionness classifier to evaluate the actionness for snippets. 
BTW, how to define a snippet, i.e. how many frames within a snippet? Thanks!

**Comment by yjxiong** [comment]
We are preparing to release the scripts to train and generate TAG proposals.

**Comment by yjxiong** [comment]
We released the TAG proposal code. Now you can run your own proposal models to get proposals for any dataset.
