### ISSUE TITLE
Indentation bug?

### ISSUE THREAD

**Issue by HYPJUDY** [yjxiong/action-detection#60]
https://github.com/yjxiong/action-detection/blob/c27d52e558690b156a6184e19846d63a87693985/ops/sequence_funcs.py#L120-L125
https://github.com/yjxiong/action-detection/blob/c27d52e558690b156a6184e19846d63a87693985/ops/sequence_funcs.py#L129-L134

should be:
``` python
for y in range(x + 1, len(up)):
    if y < len(down) and signal[up[y]] > s:
        boxes.append((up[x], down[y-1]+1, cls, sum(frm_scores[up[x]:down[y-1]+1])))
        break
    else:
        boxes.append((up[x], down[-1] + 1, cls, sum(frm_scores[up[x]:down[-1] + 1])))
```

**Comment by yjxiong** [comment]
This is not a bug. `else` after for loop is a grammar sugar in Python allowing to do something when the loop successfully completes.

http://book.pythontips.com/en/latest/for_-_else.html
