### ISSUE TITLE
the result of ssn_test.py

### ISSUE THREAD

**Issue by yanpeilun** [yjxiong/action-detection#61]
Hi yaunjun
Your work is so useful, thank you very much for your open source. I'm trying to run your code, and I want to know the meaning of the ssn_test.py result(variable rst). can you help me point them out in this code project?
thanks a lot

**Comment by yjxiong** [comment]
The usage of the score file can be found here:

https://github.com/yjxiong/action-detection/blob/master/eval_detection_results.py#L91

Do you have anything you need to use in particular?
