### ISSUE TITLE
docker about the action-detection

### ISSUE THREAD

**Issue by Ai-is-light** [yjxiong/action-detection#63]
@yjxiong Thanks for your excellent works. And you work out the tsn docker at
https://hub.docker.com/r/bitxiong/tsn/
and, I would like to know that I can run the action-detection repo code in this tsn docker??
Looking forward to your any replies

**Comment by yjxiong** [comment]
You can, if you pull this codebase to the container and install PyTorch. But the original TSN docker image does not include this codebase.
