### ISSUE TITLE
gen_proposal_list

### ISSUE THREAD

**Issue by JKANG94** [yjxiong/action-detection#65]
The program reports error as "n_pr = int(info[offset]) ValueError: invalid literal for int() with base 10: '0 0.0000 0.0000" 0.7439 0.7713' when I run gen_proposal_list.py.  I guess "if n_gt == 0:  offset += 1" in io.py is not necessary.

**Comment by LXxxxxxj** [comment]
I have the same error. Have you solved it yet?

**Comment by HCShi** [comment]
I have also met the same problem, have you solved it yet?
