### ISSUE TITLE
Question about computing the proposals' score in TAG 

### ISSUE THREAD

**Issue by happygds** [yjxiong/action-detection#68]
Hi, I have one question about computing the score of one generated proposal in TAG process. According to your code in `ops/sequence_funcs.py` file, line 122:
`boxes.append((up[x], down[y-1]+1, cls, sum(frm_scores[up[x]:down[y-1]+1])))`.
It seems that you sum all the score values inside the segment as the actionness score for this proposal. Based on this strategy, the proposal with the highest score would always be the segment that spans the whole video duration.  Does this make sense ?

**Comment by yjxiong** [comment]
Yes. Because this score is only used in the NMS step in the proposal generation, which has very strict overlap requirement. It is not used to rank the proposals anywhere else. If you want to rank the generated proposals, you may need other tools.
