### ISSUE TITLE
Questions about gen_proposal_list.py

### ISSUE THREAD

**Issue by zzw1123** [yjxiong/action-detection#69]
Hi, thanks for your great contribution!
But a problem occurs when I run gen_proposal_list.py using the command: 
python gen_proposal_list.py thumos14 thumos14

```c++
parse frames under folder thumos14
0 videos parsed
frame folder analysis done
Traceback (most recent call last):
  File "gen_proposal_list.py", line 32, in <module>
    out_list_tmpl.format(configs['train_list']), frame_dict)
  File "/data/home/huntezhang/ivyzwzhang/action-detection-scp/ops/io.py", line 40, in process_proposal_list
    frame_info = frame_dict[vid]
KeyError: 'video_validation_0000354'
```

I think the problem may be related to the thumos14 dataset. Since I notice that in the paper you mentioned that there are 220 videos in the validation set, but I have only 200.
Is this the key factor?

**Comment by lyy-zz** [comment]
I have the same doubts. Can you find a solution? @zzw1123

**Comment by yjxiong** [comment]
I guess so. You may try get the full validation set.

**Comment by lyy-zz** [comment]
I have encountered the same problem and found the reason by reading the code.
In THUMOS14 ,Validation Data (1010 untrimmed videos)，Test Data (1574 untrimmed videos),the [normalized_proposal_list](https://github.com/yjxiong/action-detection/blob/master/data/thumos14_tag_test_normalized_proposal_list.txt) corresponding to it ,but only  validation set( 200 untrimmed videos), test set (213 untrimmed videos) have annotation for action detection. 
I specified the FRAMES_PATH just have 213,so it raise KeyError.I hope this is useful to you.

But I have new doubt that have to use the no annotation video to train or test model for action  detection？@yjxiong

**Comment by yjxiong** [comment]
@lyy-zz 
Thanks for the reply. The convention for this dataset is to use videos only with positive annotations. The code we provide supports using all videos. But the results will not be apple-to-apple comparable with other methods' reports.

**Comment by ASMIftekhar** [comment]
@lyy-zz Sorry I didn't understand your solution. Can you please explain it with some more details? Thanks a lot.

**Comment by Wnaner** [comment]
> 
> 
> Hi, thanks for your great contribution!
> But a problem occurs when I run gen_proposal_list.py using the command:
> python gen_proposal_list.py thumos14 thumos14
> 
> ```c++
> parse frames under folder thumos14
> 0 videos parsed
> frame folder analysis done
> Traceback (most recent call last):
>   File "gen_proposal_list.py", line 32, in <module>
>     out_list_tmpl.format(configs['train_list']), frame_dict)
>   File "/data/home/huntezhang/ivyzwzhang/action-detection-scp/ops/io.py", line 40, in process_proposal_list
>     frame_info = frame_dict[vid]
> KeyError: 'video_validation_0000354'
> ```
> 
> I think the problem may be related to the thumos14 dataset. Since I notice that in the paper you mentioned that there are 220 videos in the validation set, but I have only 200.
> Is this the key factor?

Did you solve the problem? thank you@zzw1123
