### ISSUE TITLE
problem with gen_proposal_list.py

### ISSUE THREAD

**Issue by koji-hirakawa** [yjxiong/action-detection#70]
Hi.

I tried to use SSN.

I extracted frame images to "output"directory.
Then, I run this code.
But this error appears, and not completed.
`hogehoge:/app/action-detection# python gen_proposal_list.py thumos14 output
parse frames under folder output
0 videos parsed
200 videos parsed
Traceback (most recent call last):
  File "gen_proposal_list.py", line 29, in <module>
    frame_dict = parse_directory(args.frame_path, key_func=key_func)
  File "/app/action-detection/ops/io.py", line 80, in parse_directory
    all_cnt = count_files(f, (rgb_prefix, flow_x_prefix, flow_y_prefix))
  File "/app/action-detection/ops/io.py", line 73, in count_files
    lst = os.listdir(directory)
OSError: [Errno 40] Too many levels of symbolic links: 'output/video_test_0000966'
`

I tried to solve this error, but I couldn't.
(for example: I made a symbolic links in ../output)

Please someone tells me the good way to solve this problem.

**Comment by yjxiong** [comment]
`Too many levels of symbolic links: 'output/video_test_0000966'`

Are you making self-looped symbolic links \?

**Comment by koji-hirakawa** [comment]
I cheked again and found the self-looped symbolic links.
Thank you!!
However, new problem appeared.
I ran this command.
`python3 ssn_train.py thumos14 RGB -b 16 --lr_steps 20 40 --epochs 45`
I got  new error
`RuntimeError: cuda runtime error (2) : out of memory at `
Then, I read [#26](https://github.com/yjxiong/action-detection/issues/26).
I tried this code
`python ssn_train.py thumos14 RGB -b 1 -i 16 --lr_steps 320 640 --epochs 720`
The error didn't appear.
Do I need to change learning rate when I use above command???

**Comment by yjxiong** [comment]
It means your GPU doesn't have enough memory or you have too few GPUs installed. Its recommend to 4~8 GPUs with 12G memory. You can try a smaller batchsize if you don't have that I cannot guarantee the accuracy.

**Comment by pengxiaoxiao** [comment]
Why is thumos 14 _ tag _ val _ normalized _ proposal _ list.txt having so many videos, isn't it 413 in total verified and tested?

**Comment by Wnaner** [comment]
> 
> 
> Why is thumos 14 _ tag _ val _ normalized _ proposal _ list.txt having so many videos, isn't it 413 in total verified and tested?

Do you know why?@pengxiaoxiao
