### ISSUE TITLE
The SSN in a demo form

### ISSUE THREAD

**Issue by mikeleatila** [yjxiong/action-detection#71]
Hello, I am able to run your PyTorch SSN code and I can get it running in all the segments (ssn_train, ssn_test, evaluate_detection_results parts). Also the SSN project should output starting time, ending time, and category for each action instance (of an input video). I want to create a demo based on your code, and for an input video, output the starting time, the ending time, and the label of activity(ies) detected in that video but not sure where I can find this information in the ssn_test.py/eval_detection_results.py scripts? Could anyone maybe help me about this? Many thanks in advance! @yjxiong

**Comment by v-iashin** [comment]
@mikeleatila have you succeded with this?

**Comment by yushuinanrong** [comment]
+1
