### ISSUE TITLE
sequence_funcs.py

### ISSUE THREAD

**Issue by xuesong0309** [yjxiong/action-detection#72]
line 134 in sequence_funcs.py：
boxes.append((up[0], down[x] + 1, cls, sum(frm_scores[0:down[x]+1 + 1])))
should be
boxes.append((up[0], down[x] + 1, cls, sum(frm_scores[up[0]:down[x]+1])))
?
I‘m looking forward to your reply.

**Comment by yjxiong** [comment]
Yes. Thanks.

Fiexed in e88344b2c88df28a8794fd6fce5cf544f52f1e9e
