### ISSUE TITLE
Training on a different dataset

### ISSUE THREAD

**Issue by fmthoker** [yjxiong/action-detection#75]
@yjxiong  could you share some guide for training SSN on a different dataset like PKU-MMD?

**Comment by yjxiong** [comment]
You can follow the instruction to generate proposals using the provided actionness model. Then you can train the SSN detection following README.

**Comment by fmthoker** [comment]
@yjxiong  Thanks for your amazing work, and response. I will try that

**Comment by fmthoker** [comment]
@yjxiong  Thanks again.  I just want to confirm whether I got the whole process correct, 

First,  I have to use your provided actioness models  i:e
   python binary_test.py  mydataset  MODALITY train  "your checkpoints " ACTIONNESS_RESULT_PICKLE 
followed by 
python gen_bottom_up_proposals.py ACTIONNESS_RESULT_PICKLE  --dataset  mydataset  --subset train  --write_proposals data/mydataset_tag_train_proposal_list.txt  --frame_path mydataset_FRAME_PATH.

However, I have one confusion when I run binary test command it:  I get this error
  [Errno 2] No such file or directory: 'data/pkummd_sw_train_proposal_list.txt'
My question is now what should be the content of this file for my dataset. 
I checked the wiki which describes proposal file as:
# INDEX
VIDEO_ID
NUM_UNITS
FPS
NUM_GT
(CLASS START END) x NUM_GT
NUM_PROP
(CLASS MAX_IOU MAX_OVERLAP START END) x NUM_PROP

I can create such a file from my annotations but I am not sure how to obtain the last two rows for my dataset.

**Comment by yjxiong** [comment]
You wrote the proposal to `data/mydataset_tag_train_proposal_list.txt` but you are asking the codebase to use proposals `data/pkummd_sw_train_proposal_list.txt`. I guess you should make the filenames consistent.

**Comment by fmthoker** [comment]
Sorry for the confusion, Actually I didn't write any proposal file yet. I have updated the above comment.
My question is actually about how do I generate the proposal file. 
I checked the wiki which describes proposal file as:
# INDEX
VIDEO_ID
NUM_UNITS
FPS
NUM_GT
(CLASS START END) x NUM_GT
NUM_PROP
(CLASS MAX_IOU MAX_OVERLAP START END) x NUM_PROP

I can create such first 5 rows from my annotations but I am not sure how to obtain the last two rows for my dataset.

**Comment by fmthoker** [comment]
Done now

**Comment by ASMIftekhar** [comment]
Hey, @fmthoker  how did you generate proposal on some other videos?
