### ISSUE TITLE
Regenerating TAG proposals on ActivityNet v1.2

### ISSUE THREAD

**Issue by mikeleatila** [yjxiong/action-detection#77]
Hello @yjxiong, @Tonyfy, I am trying to regenerate proposals on ActivityNet v1.2 (in order to run the ssn algorithm afterwards) using your code to train binary actionness classifiers and generate proposals (TAG). I have successfully generated sliding window proposals (for both training and validation for RGB and Flow parts) and then trained binary actionness classifier for 8 epochs (for RGB and Flow parts) and finally obtained actionness score (for both training and validation for RGB and Flow parts) with no issues reported during these processes. Then I wanted to generate TAG proposals using gen_bottom_up_proposals.py and I got EMPTY activitynet1.2_tag_train_proposal_list.txt & activitynet1.2_tag_val_proposal_list.txt files with following console output:

Got 100 leaf classes out of 151
There are 4819 videos for training, 2383 for validation, 2480 for testing
There are 7151 instances for training, 3582 for validataion
loaded 9032 video folders
video list size: 2383
loading scores...
load 1 piles of scores
done
merging scores
done
generating proposals
0 groundtruth boxes from
/data/users/dek/anaconda3/envs/dek_python3_env/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
average # of proposals: nan
IOU threshold 0.5. per video recall: 0.000000, per instance recall: 0.000000
IOU threshold 0.7. per video recall: 0.000000, per instance recall: 0.000000
IOU threshold 0.8999999999999999. per video recall: 0.000000, per instance recall: 0.000000
Average Recall: 0.0000 0.0000
/data/users/dek/anaconda3/envs/dek_python3_env/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
list written. got 0 videos

Process finished with exit code 0

Also during the debugging process when running gen_bottom_up_proposals.py I can see that all these variables are empty lists (except score_list): 

proposal_list = [pr_dict[v.id] for v in video_list if v.id in pr_dict]
gt_spans_full = [[(x.num_label, x.time_span) for x in v.instances] for v in video_list if v.id in pr_dict]
gt_spans = [[item[1] for item in x] for x in gt_spans_full]
score_list = [score_dict[v.id] for v in video_list if v.id in pr_dict]
duration_list = [v.duration for v in video_list if v.id in pr_dict]
proposal_score_list = [pr_score_dict[v.id] for v in video_list if v.id in pr_dict]

Could you please let me know why I cannot generate TAG proposals correctly?

Many thanks and with best regards!

**Comment by mikeleatila** [comment]
Fixed so closing down

**Comment by tingbao** [comment]
I have the same problem. Can you tell me how to solved it?

**Comment by mikeleatila** [comment]
Hello @tingbao , Actually I had a problem with this script:

https://github.com/yjxiong/action-detection/blob/master/gen_bottom_up_proposals.py

Since the video folders are in this form: v_XXX ... XX what made it work at the end, is to add this representation:

1) in line 118 should be: vid = "v_" + v.id

2) in line 162 should be: score_list = [score_dict["v_" + v.id] for v in video_list if v.id in pr_dict]

Hope this helps!

**Comment by mikeleatila** [comment]
Has this solved your problem @tingbao ?
