### ISSUE TITLE
Question about actionness score

### ISSUE THREAD

**Issue by xuesong0309** [yjxiong/action-detection#79]
Hi. I have some questions about actionness scores. The dimension of the output from binary_test.py is num_frame by 2. It is said in your paper that values of the  actionnness scores ranged from 0 to 1. I have seen  the output[:,0] and output[:,1], and none of them meet this range. So I don't know which one is actionness score and how to group consecutive snippets with high actionness scores. 
According to your code in ops/sequence_funcs.py file, line 122:
boxes.append((up[x], down[y-1]+1, cls, sum(frm_scores[up[x]:down[y-1]+1])))
Is this frm_scores that actionness scores?

**Comment by yjxiong** [comment]
The binary output means there are two classes. To get the 0-1 values, the code does a SoftMax normalization.
