### ISSUE TITLE
problem of proposal_list

### ISSUE THREAD

**Issue by gss-ucas** [yjxiong/action-detection#8]
Hi, @yjxiong can you release your proposal_list? When I use my generated proposal_list file, testing is always wrong, it says that math domain error, maybe because gt_size < prop_size in 

> def compute_regression_targets(self, gt_list, fg_thresh):

 in ssn_dataset.py

**Comment by yjxiong** [comment]
They are already there in the form of relative duration.

For example,
https://github.com/yjxiong/action-detection/blob/master/data/thumos14_tag_val_normalized_proposal_list.txt


If still meet errors, better post the full stack trace.

**Comment by gss-ucas** [comment]
@yjxiong I fixed it by float(gt_size), and fixed other error by this operation. In python, if a and b are integers and a<b, then a/b==0, so I must change them to floats.
I'm so curious why I had this error but you didn't, do you know the reason?
By the way, does the completeness classifier has a sigmoid layer??

**Comment by yjxiong** [comment]
Are you using Python 2.x? I wrote the code with Python 3.5. Perhaps we should some compatibility fixes to the codebase.

**Comment by gss-ucas** [comment]
@yjxiong yes, I'm using python 2.7, I also think it's due to the different version.

**Comment by yjxiong** [comment]
Good. 
Closing this. Please feel free to reopen it if you meet any further problem.
