### ISSUE TITLE
How to use tsn to train actionness classifiers? 

### ISSUE THREAD

**Issue by canbaoburen** [yjxiong/action-detection#82]
Hello, in the paper 'A Pursuit of Temporal Accuracy in General Activity Detection', it is said 'To evaluate the actionness, we learn a binary classifier based on the Temporal Segment Network proposed in [37]. It uses whole videos to train two stream CNNs in order to model the long-range temporal dynamics. In our practice, we modify it to take regions inside videos as input.'  I don't understand what it mean. TSN is usually used to encode a long-range region consists of multiple segments by using a aggregation function,  while the snippets in this paper are small. How to use TSN on single snippet? Hope to receive your reply soon.

**Comment by yjxiong** [comment]
You can look at the implementation of TAG in this codebase, especially the `binary_train.py` part.
