### ISSUE TITLE
Very bad test result on THUMOS14

### ISSUE THREAD

**Issue by Pea-Shooter** [yjxiong/action-detection#83]
After evaluated on THUMOS14(used both the model of mine and your reference model), I got the test result as follows:

+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------
+                                                                                                       
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average 
|                                                                                                       
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------
+                                                                                                       
| mean AP    | 0.0066 | 0.0039 | 0.0021 | 0.0011 | 0.0005 | 0.0002 | 0.0000 | 0.0000 | 0.0000 | 0.0016  
|                                                                                                       
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------
+                                                                                                   

It is incredibly bad, and I spent a lot of time to figure out this problem but the result is still. Have you ever met this problem or can you give me some instructions?

**Comment by yjxiong** [comment]
We haven't met this. I guess you can check either the proposal list or the video data you use.
