### ISSUE TITLE
AR about the TAG

### ISSUE THREAD

**Issue by lyy-zz** [yjxiong/action-detection#84]
I download the Pretrained actionness classifier on THUMOS14，and run the `binary_test.py` to get the action score. Then run the `gen_bottom_up_proposals.py` to get the result, as follows:
I noticed that #15 ,so change the IOU_thresh to [0.5,0.95,0.05] on line170
```
average # of proposals: 212.375
.....
Average Recall: 31.4444 55.3948
```
The AR in the paper is 48.9, I have no idea which one of the above result，or have another convention methods to eval ??? and the above result is well or bad ???

**Comment by yjxiong** [comment]
You may use the results in the paper for comparison.
