### ISSUE TITLE
Standard video input fps (frame per second)?

### ISSUE THREAD

**Issue by intheroom** [yjxiong/action-detection#89]
I wonder will video's fps affect how we config interval. For example, if we extract frames with an interval of 6 on a 30fps video we will get more frames than if we extract optical flow on 10fps one. So my question is what the standard fps of the input video is?

_Originally posted by @intheroom in https://github.com/yjxiong/action-detection/issues/18#issuecomment-458878823_

**Comment by yjxiong** [comment]
generally 15-30FPS should be ok. As long as you use the same optical flow extraction FPS in both training and testing it is fine.
