### ISSUE TITLE
Documentation request: optical flow file format, image size, file naming etc

### ISSUE THREAD

**Issue by jackkwok** [yjxiong/action-detection#91]
For some reason, no matter what I tried, I kept on getting errors with compiling openCV dependency on TSN repo.

Instead of using the optical flow tools in TSN repo, I'd rather generate my own optical flow with my own code.  Can you add documentation on the exact spec (file format, image size, file naming etc) of the optical flow files and the frame files?  This way I won't have dependency on TSN repo.

Thanks!

**Comment by yjxiong** [comment]
We have provide docker image for you to use. You dont' need to manually compile them. Please see README

**Comment by jackkwok** [comment]
Thanks for your response.  I am aware of the docker image but I am not allowed to use the docker image in my work environment.
