### ISSUE TITLE
How to create normalized proposal list from my own dataset?

### ISSUE THREAD

**Issue by jalaxy33** [yjxiong/action-detection#97]
Hi, @yjxiong .

I am trying to generate proposal list from my own dataset. I need to generate a normalized proposal list first, based on [the Guide](https://github.com/yjxiong/action-detection#prepare-the-proposal-lists) and [the code](https://github.com/yjxiong/action-detection/blob/master/gen_proposal_list.py) you provided. There is no explicit guidance and api, so I feel confused. By the way, I have successfully extracted frames and flow images using the [TSN](https://github.com/yjxiong/temporal-segment-networks) you provided.

I have being stuck on this problem for a long time. So could you please show me more detials about how to generate normalized proposal list from my own dataset?

**Comment by xianguo-dev** [comment]
Hi！ Have you succeed？I have the same question.

**Comment by mrlihellohorld** [comment]
Have you succeed？I have the same question.
