### ISSUE TITLE
question about proposal_list

### ISSUE THREAD

**Issue by Wnaner** [yjxiong/action-detection#98]
Do we need to extract frames and opticalflow images for all the video in Thumos2014 validation and test(totally 1010+1054 videos)? 
When I only need to use videos with annotions for temporal action dection ,do  we need to  extract frames and opticalflow images for all the video? Cause I spent many time in this step. But when I use only 200+213 videos I meet problem in step generate  sliding-window proposals. Can you give me some advise?

**Comment by yjxiong** [comment]
You can refer to [MMAction](https://github.com/open-mmlab/mmaction) for the latest steps in experiments.
